# 1. Deep Learning

Bienvenidos al módulo de Deep Learning. En esta sesión vamos a ver una breve introducción con las diferencias entre Inteligencia Artificial, Machine Learning y Deep Learning. También hablaremos un poco de cuanto tiempo lleva este mundillo en marcha, e introduciremos el gradient descent, el pilar fundamental de las redes neuronales.

En la segunda parte empezaremos a trabajar con TensorFlow, y al terminar, habréis implementado vuestra **primera red neuronal**!

Aquí tenéis el temario que cubriremos hoy:

**Introducción**
* Del Machine Learning al Deep Learning
* Contexto histórico
* Herramienta: Google Colab
* Descenso del gradiente

**Introducción a TensorFlow**
* Grafos, variables, operaciones
* Resolución de problemas con TensorFlow
* Mi primera red neuronal en TensorFlow

¿Qué os parece? ¿Tenéis ganas?

**¡Vamos allá!**

## 1.1. Introducción. Del Machine Learning al Deep Learning.

¿Qué es el Deep Learning? ¿En qué se diferencia del Machine Learning? ¿Y de la Inteligencia Artificial?

<a href="https://ibb.co/hWqjG7"><img src="https://preview.ibb.co/cETFOn/AI_ML_DL.png" alt="IA engloba ML, que a su vez engloba DL" border="0"></a>

**Inteligencia artificial:** 

La IA consiste en conseguir que las máquinas realicen tareas que requieren de la inteligencia humana. Se puede dividir en dos campos:

*   *General AI*: consiste en dotar a las máquinas de todas nuestras capacidades y sentidos. Por ejemplo, C-3PO o Terminator. Tranquilos, todavía queda muuuucho para ver algo parecido a Skynet por aquí.
*   *Narrow AI*: consiste en dotar a las máquinas de la capacidad de desarrollar una determinada tarea, como por ejemplo, reconocer caras, señales de tráfico, el habla, etc. Es en este campo donde actualmente se están observando grandes avances.

**Machine Learning:**

El Machine Learning o aprendizaje máquina es un **subcampo dentro de la Inteligencia Artificial**. Básicamente, consiste en **utilizar una gran cantidad de datos para extraer información útil para las personas**. Por ejemplo, imaginaos que disponemos de los últimos resultados de La Liga y queremos ser capaces de predecir el resultado del próximo Clásico. Primero, necesitariamos *parsear* los datos, limpiarlos, eliminar las entradas incompletas, estudiar la distribución de las variables y elegir las características o atributos (*feature engineering*) que nos permitieran predecir este resultado con la mayor precisión posible. Una vez tuviésemos claro cuales son las mejores características a utilizar, necesitaríamos encontrar el mejor algoritmo posible para nuestro dataset.

La **elección de las características**, que a priori puede llegar a parecer sencillo, es el paso **más complicado y costoso** y, además, requiere de un alto grado de conocimientos sobre el problema en cuestión y sobre técnicas de extracción de características.

**Deep Learning:**

El aprendizaje profundo o Deep Learning es un subcampo del **Machine Learning**, y soluciona el problema anterior de la elección de características. También llamado aprendizaje jerárquico, ***aprende*** distintas **representaciones de los datos** que son introducidas a un clasificador final.

La magia está en que ya no necesitamos volvernos locos buscando las mejores características o atributos para cada problema, si no que esto lo hace **automáticamente** nuestro algoritmo.


Por último, cabe destacar la importancia de tener una gran cantidad de datos para poder utilizar técnicas de ML o DL. Además, cuanta más calidad tengan esos datos, mejor se comportaran nuestros modelos.

*“I think AI is akin to building a rocket ship. You need a huge engine and a lot of fuel. If you have a large engine and a tiny amount of fuel, you won’t make it to orbit. If you have a tiny engine and a ton of fuel, you can’t even lift off. To build a rocket you need a huge engine and a lot of fuel.”*

– Andrew Ng (source: Wired)

Que traducido quiere decir:

*Creo que la IA es parecido a construir un cohete espacial. Necesitas un motor enorme y mucho combustible. Si tienes un motor enorme pero poco combustible, no conseguirás poner el cohete en órbita. Si tienes un pequeño motor y un montón de combustible, no podrás ni despegar. Para construir un cohete espacial necesitas un motor enorme y un monton de combustible.*

Así que ya sabéis, no solo es importante el algoritmo que utilicemos, sino los datos de los que dispongamos.

¿Y por qué **deep** learning?

<img src="https://www.tensorflow.org/images/wide_n_deep.svg" border="0" height="300">

Porque realizamos muchas transformaciones a los datos que tenemos, una detrás de la otra, de una forma secuencial, hasta que llegamos a la representación de esos datos en la que somos capaces de diferenciar los datos conforme nosotros queremos.

Aquí tenéis un muy buen ejercicio que podéis hacer cuando tengáis un rato: https://www.tensorflow.org/tutorials/wide_and_deep

### 1.1.1. Contexto histórico

Probablemente muchos de vosotros penséis que esto del Deep Learning y las redes neuronales es una novedad, pues nada más lejos de la realidad! De hecho, la primera red neuronal data de 1958!! Lo que pasa es que no había potencia de cálculo suficiente para poder progresar hasta hace relativamente poco, con la popularización de las GPUs de altas prestaciones. Así que... gracias gamers!!

Por si tenéis curiosidad, estas son las cosas más importantes que han ido pasando dentro del campo de la IA:

<img src="https://image.ibb.co/mEVbA8/timeline_deep_learning.png" alt="timeline_deep_learning" border="0">

*   **1950**: Alan Turing crea el **Test de Turing**
*   **1952**: Arthur Samuel crea el primer programa que **aprende** partida tras partida a jugar a las Damas
*   **1956**: Martin Minsky acuña el término **"Artificial Intelligence"** para referirse a este nuevo campo
*   **1958**: Frank Rosenblatt diseña el Perceptrón, **la primera red neuronal artificial**. HACE **60 AÑOS!!!**

Como podéis ver, la Inteligencia Artificial no es ni mucho menos nueva, lleva mucho tiempo entre nosotros, sufriendo altibajos debidos a las altas expectativas depositadas y los "pocos" avances conseguidos.

Desde 1974 hasta nuestros días, se han producido varios "inviernos" y "primaveras".

<a href="https://imgbb.com/"><img src="https://image.ibb.co/b3ih3n/AI_winter.jpg" alt="Winter is coming" border="0"></a>

Algunos de los hechos más relevantes hasta 2006 son estos:

*   **1967**: Nace el campo del reconocimiento de patrones con la aparición del algoritmo **"Nearest Neighbor"**
*   **1979**: Crean el Stanford Cart, un **robot capaz de navegar automáticamente por una habitación evitando obstáculos**
*   **1981**: Gerald Dejong introduce el "Explanation Based Learning", el precursor del Machine Learning. El ordenador **analizaba datos** de entrenamiento y creaba reglas **para descartar los datos menos importantes**
*   **1985**: Terry Sejnowski inventa NetTalk, un algoritmo capaz de **aprender a pronunciar palabras** como lo haría un niño
*   **1990s**: **Cambia el paradigma del Machine Learning**: de un enfoque orientado al conocimiento, a uno **orientado al dato**. Empiezan a extraer conclusiones de grandes cantidades de datos.
*   **1997**: **DeepBlue derrota a Kaspárov** por primera vez.

Tras esta época de luces y sombras, y gracias, entre otras cosas, a la disponibilidad de mucha más potencia de cálculo y de datos, desde 2006 hasta la fecha ha habido una explosión del Machine Learning.

*   **2006**: Aparecen las **arquitecturas profundas**, acuñadas como Deep Learning por Geoffrey Hinton
*   **2011**: **Watson IBM vence** a sus competidores **humanos** en el concurso Jeopardy
*   **2012**: Geoffrey Hinton gana por goleada el concurso de **ImageNet** con una red neuronal profunda
*   **2012**: En Google X crean GoogleBrain, capaz de **detectar gatos en videos**
*   **2014**: Facebook desarrolla DeepFace, capaz de **reconocer caras de humanos con una precisión de 97.25%**, solo un 0.28% por debajo de un ser humano
*   **2014**: Google compra DeepMind, una stertup inglesa que había creado un algoritmo capaz de **aprender a jugar con juegos Atari simplemente viendo el video**
*   **2015**: Elon Musk y Sam Altman crean OpenAI para **promover el bueno uso de la IA**
*   **2016**: **Google DeepMind vence** por primera vez en el **juego Go, consiguiendo movimientos creativos**

### 1.1.2. Google Colab

La plataforma en la que os encontráis se llama **Google Colab**. Va a ser a la vez nuestro *notebook* y nuestra IDE, ya que nos permite aprovechar que por el momento Google ofrece GPUs **NVIDIA K80** de forma **gratuita** (maravilloso, no?), que es donde ejecutaremos nuestros desarrollos.

Cualquiera con una cuenta de Google puede crear un nuevo notebook y empezar a disfrutarlo! A lo largo del curso iremos viendo lo necesario para que aprendáis a manejarlo con soltura, así que no tenéis por qué preocuparos si es la primera vez que lo véis. Y si habéis trabajado antes con Jupyter, esto es lo mismo!

Lo único que tenéis que hacer todos para aprovechar la GPU es ir a **Edit**, en la barra de herramientas, y luego a **Notebook settings**. Os aparecerá esta pantalla, la cual tiene que quedar igual que en la imagen. Debéis seleccionar Python 3 y GPU, y luego darle a **Save**.

<a href="https://ibb.co/ceoX3n"><img src="https://preview.ibb.co/mQEi9S/notebook_config.png" alt="Notebook configuration" border="0"></a>

### 1.1.3. El descenso del gradiente: el culpable de que existan las redes neuronales

El mecanismo que hace que una red neuronal aprenda es el descenso del gradiente. Como posiblemente ya sabréis los más curiosos, las redes neuronales se entrenan actualizando una serie de pesos, y conforme más se entrenan, más se acercan a una buena solución. ¿Os suena esto de algo?


¿No?


¡Estamos optimizando funciones! En efecto, siento desilusionaros, pero las redes neuronales no son otra cosa que un método, muy ingenioso y potente, eso sí, de **optimizar funciones**. Y nuestro mejor amigo se llama **Descenso del gradiente**, que es lo que en gran medida ha permitido que podamos entrenar redes con millones de parámetros y vivir para verlo!

**¿Pero qué es el descenso del gradiente?**

Vamos a imaginarnos que estamos en lo alto de una montaña y que hay una niebla tremenda, con lo cual no somos capaces de ver más allá de nuestras narices, literalmente. Lo que queremos lógicamente es llegar abajo del todo, donde hay un bar estupendo con una cervecita bien fría esperándonos. Aunque más de uno puede que haya saltado ya y no le importe bajar rodando, para aquellos más cautos, os voy a explicar cómo lo vamos a hacer. Poneos en situación. Estáis en el punto más alto y no veis nada, ¿cómo lo hacéis para bajar la montaña?

<img src="https://image.ibb.co/jhnVbJ/mountain.png" alt="mountain" border="0" height="300">

¿Ningún valiente? Ya he dicho que rodando no nos vale.

¿Y si damos un pequeño paso en cada una de las 4 direcciones (este, oeste, norte y sur) y elegimos aquella en la que más bajamos para dar un paso? ¿Y si volvemos a realizar esta operación una y otra vez? Podríamos hacer esto hasta que no consiguieramos bajar en ninguna de las 4 posibles orientaciones. Entonces, en teoría, deberíamos haber llegado abajo.

¿Qué? ¿No os termina de convencer verdad? Eso de dar 4 pasos a ver cual es mejor... no pareece muy eficiente ¿verdad? ¿Se os ocurre alguna forma de mejorar esto? Ojalá hubiese alguna forma de saber qué pendiente hay en cada punto, no? eso nos permitiría avanzar siempre hacia donde más pendiente hubiera.

¿Os suena esto de algo? ¿Cómo podemos averiguar la pendiente de una función?

¡Eso es! ¡Calculando la **derivada**!

¿Os acordáis de qué es lo que indica la derivada de una función? ¿Os acordáis de cómo se calculan?

$f'(x) = \frac{f(x+h)-f(x-h)}{2}$, cuando $h\to 0$.

La primera derivada de una función mide la rapidez con que cambia una función, es decir cuanto crece o decrece. Así que lo que podemos hacer es **calcular la pendiente para cada punto al que llegamos seguir bajando esa pendiente hasta un punto mínimo**.

<img src="https://image.ibb.co/cXGCqd/mountain_gd.png" alt="mountain_gd" border="0" height="300"> <img src="https://image.ibb.co/ganZLd/gradient_descent_2.png" alt="gradient_descent_2" border="0" height="300">

Pues si amigos, esto taaaan sofisticado es el algoritmo del descenso del gradiente, y os puedo decir que es **el corazón de las redes neuronales**.

Para aquellos de vosotros que os gusten más las matemáticas que las montañas, podéis ver el descenso del gradiente como un algoritmo de optimización que permite **minimizar cualquier función** (siempre que sea **diferenciable**, es decir, que podamos calcular sus derivadas). De hecho, la idea es muy similar a aquellos problemas de optimización a los que muy posiblemente os hayáis enfrentado en alguna clase de matemáticas a lo largo de vuestras vidas. Y para muestra, un botón:

<center><img src="http://www.cs.us.es/~fsancho/images/2017-02/gradient_descent.gif" border="0"></center>

Este algoritmo tiene variaciones (vanilla gradient descent, batch gradient descent, stochastic gradient descent, etc), pero todos parten de la misma idea base, la que os acabo de explicar.

## 1.2. Introducción a TensorFlow

Como muchos de vosotros ya sabréis, TensorFlow es un framework desarrollado y mantenido por Google que permite la ejecución de operaciones matemáticas de una forma optimizada en una CPU o GPU. En nuestro caso estamos más interesados en la GPU, ya que es la única forma que tenemos de entrenar una red neuronal profunda y no morir de viejos esperando ;)

¿Por qué tensorflow?

* Por su **flexibilidad y escalabilidad**

* Por su **popularidad**

<img src="https://image.ibb.co/mCJNqd/tf_pop.png" alt="tf_pop" border="0" height="300"> <img src="https://image.ibb.co/bBDYwJ/tf_users.png" alt="tf_users" border="0" height="300">


Más adelante comprenderemos por qué es tan importante disponer de un buen framework que nos permita realizar operaciones de la forma más rápida posible. De momento, vamos a trabajar un poco con TensorFlow hasta que nos familiaricemos con su modo de funcionar. Pero antes, algunas de sus características más importantes:

*    TensorFlow utiliza **tensores** para realizar las operaciones.
*    En TensorFlow, primero se definen las operaciones a realizar (construimos el **grafo**), y luego se ejecutan (se ejecuta el grafo)
*    Permite ejecutar el código implementado **paralelamente** o en una o varias GPUs, a elección del usuario

Vale, pero **¿qué es un tensor?**

Aunque los tensores los inventaron los físicos para ser capaces de describir interacciones, en el ámbito de la IA se pueden entender simplemente como **contenedores de números**.

<a href="https://ibb.co/bBCyb7"><img src="https://image.ibb.co/fnFvOn/tensores.png" alt="tensores" border="0"></a>

In [0]:
# Vamos a practicar con nuestros nuevos mejores amigos, los Tensores
import numpy as np

# Imaginaos que queréis guardar la nota media del máster de Tristina Cipuentes.
# Para ello utilizaríais un tensor de 0D, que no es otra cosa que un simple 
# número, también conocido como escalar.

# Tensor 0D (escalar)
tensor_0D = np.array(5)
print("Nota media:\n{}".format(tensor_0D))
print("Dimensiones del tensor: {}".format(tensor_0D.ndim))

Nota media:
5
Dimensiones del tensor: 0


In [0]:
# Pero con una sola nota no habría mucho que defender, podría decirse incluso
# que alguien se la ha inventado, así que mejor si guardamos las notas de
# TODOS las asignaturas que hizo. Podemos usar un tensor 1D para ello:

# Tensor 1D (vector)
tensor_1D = np.array([2, 8, 6])
print("Notas de las asignaturas:\n{}".format(tensor_1D))
print("Dimensiones del tensor: {}".format(tensor_1D.ndim))

Notas de las asignaturas:
[2 8 6]
Dimensiones del tensor: 1


In [0]:
# Un momento... ¿no sería mejor que nos guardásemos la puntuación de cada 
# examen de cada asignatura? ¿Cómo podríamos hacerlo, si cada asignatura consta 
# de 3 exámenes? ¿Se os ocurre alguna estructura que nos lo permita?

# En efecto, un tensor 2D!

# Tensor 2D (matriz)
tensor_2D = np.array([[0, 1, 1],  # asignatura 1
                      [2, 3, 3],  # asignatura 2
                      [1, 3, 2]])  # asignatura 3
print("Las puntuaciones de Tristina en sus exámenes son:\n{}".format(tensor_2D))

print("Asignatura 1:\n{}".format(tensor_2D[0]))

print("Asignatura 2:\n{}".format(tensor_2D[1]))

print("Asignatura 3:\n{}".format(tensor_2D[2]))

print("Dimensiones del tensor: {}".format(tensor_2D.ndim))

Las puntuaciones de Tristina en sus exámenes son:
[[0 1 1]
 [2 3 3]
 [1 3 2]]
Asignatura 1:
[0 1 1]
Asignatura 2:
[2 3 3]
Asignatura 3:
[1 3 2]
Dimensiones del tensor: 2


In [0]:
# Sin embargo, como nosotros somos muy ordenados y no queremos que se nos pierda
# nada, mejor si guardamos las notas de las asignaturas (que son anuales) por 
# cuatrimestres, así será más fácil acceder a ellas si hiciese falta en un 
# futuro, ¿no os parece? ¿Cómo se os ocurre que podríamos organizarlas?

# ¿Y si añadimos una dimensión a nuestro tensor 2D que indique el cuatrimestre?

# Tensor 3D (matriz 3D o cubo)
tensor_3D = np.array([[[0, 1, 1],  # Primer cuatrimestre
                      [2, 3, 3],
                      [1, 3, 2]],
                     [[1, 3, 2],  # Segundo cuatrimestre
                      [2, 4, 2],
                      [0, 1, 1]]])
print("Las notas de Tristina por cuatrimestre son:\n{}".format(tensor_3D))

print("Primer cuatrimestre:\n{}".format(tensor_3D[0]))

print("Segundo cuatrimestre:\n{}".format(tensor_3D[1]))

print("Dimensiones del tensor: {}".format(tensor_3D.ndim))

Las notas de Tristina por cuatrimestre son:
[[[0 1 1]
  [2 3 3]
  [1 3 2]]

 [[1 3 2]
  [2 4 2]
  [0 1 1]]]
Primer cuatrimestre:
[[0 1 1]
 [2 3 3]
 [1 3 2]]
Segundo cuatrimestre:
[[1 3 2]
 [2 4 2]
 [0 1 1]]
Dimensiones del tensor: 3


In [0]:
# ¿Qué os parece? Ya tenemos perfectamente guardadas las notas de Tristina,
# para que no se pierdan. ¿Pero qué pasa con los demás alumnos? ¿Se os ocurre
# cómo podríamos guardarnos sus notas también?
# ¿Y si añadimos una dimensión a nuestro tensor, de forma que podamos tener las
# notas por cuatrimestre de cada asignatura para cada alumno?

# Tensor 4D (vector de matrices 3D o vector de cubos)
tensor_4D = np.array([[[[0, 1, 1], # Tristina
                      [2, 3, 3],
                      [1, 3, 2]],
                     [[1, 3, 2],
                      [2, 4, 2],
                      [0, 1, 1]]],
                      [[[0, 3, 1], # Facundo
                      [2, 4, 1],
                      [1, 3, 2]],
                     [[1, 1, 1],
                      [2, 3, 4],
                      [1, 3, 2]]],
                     [[[2, 2, 4], # Celedonio
                      [2, 1, 3],
                      [0, 4, 2]],
                     [[2, 4, 1],
                      [2, 3, 0],
                      [1, 3, 3]]]])
print("Las notas de Tristina, Facundo y Celedonio por cuatrimestre son:\n{}".format(tensor_4D))

print("Notas de Tristina:\n{}".format(tensor_4D[0]))

print("Notas de Facundo:\n{}".format(tensor_4D[1]))

print("Notas de Celedonio:\n{}".format(tensor_4D[2]))

print("Dimensiones del tensor: {}".format(tensor_4D.ndim))

Las notas de Tristina, Facundo y Celedonio por cuatrimestre son:
[[[[0 1 1]
   [2 3 3]
   [1 3 2]]

  [[1 3 2]
   [2 4 2]
   [0 1 1]]]


 [[[0 3 1]
   [2 4 1]
   [1 3 2]]

  [[1 1 1]
   [2 3 4]
   [1 3 2]]]


 [[[2 2 4]
   [2 1 3]
   [0 4 2]]

  [[2 4 1]
   [2 3 0]
   [1 3 3]]]]
Notas de Tristina:
[[[0 1 1]
  [2 3 3]
  [1 3 2]]

 [[1 3 2]
  [2 4 2]
  [0 1 1]]]
Notas de Facundo:
[[[0 3 1]
  [2 4 1]
  [1 3 2]]

 [[1 1 1]
  [2 3 4]
  [1 3 2]]]
Notas de Celedonio:
[[[2 2 4]
  [2 1 3]
  [0 4 2]]

 [[2 4 1]
  [2 3 0]
  [1 3 3]]]
Dimensiones del tensor: 4


Y así podríamos seguir hasta el infinito añadiendo dimensiones a nuestros tensores para ser capaces de guardar más datos. Para que os hagáis una idea de cómo se suelen utilizar en el mundo del Deep Learning, los tipos más comunes de tensores son:

*    **Tensores 3D**: utilizados en **series temporales**
*    **Tensores 4D**: utilizados con **imágenes**
*    **Tensores 5D**: utilizados con **videos**

Normalmente, siempre habrá una de las dimensiones que se utilizará para almacenar las muestras de cada tipo de datos. Por ejemplo, con las imágenes:

Si queremos almacenar 64 imágenes RGB de 224x224 píxels, necesitaremos un vector de matrices 3D, o lo que es lo mismo, un tensor 4D. ¿Quién sabría decirme las dimensiones que tendría nuestro vector de matrices 3D?

Tenemos 64 imágenes de 224 pixels x 224 pixels x 3 canales (R, G y B). 

Por tanto: (64, 224, 224, 3)

De acuerdo, pues ya sabemos qué es un tensor y para que sirve: ¡para mantener las notas de vuestros exámenes bien guardadas! ;D

Si queréis profundizar en los tensores o más ejemplos, aquí tenéis un recurso muy bueno para ello (en inglés): [Tensors ilustrated with cats](https://hackernoon.com/learning-ai-if-you-suck-at-math-p4-tensors-illustrated-with-cats-27f0002c9b32)

Antes os he comentado que en TensorFlow, primero se definen las operaciones a realizar y luego se ejecutan. Para ello, se usa un grafo.

**¿Y qué es un grafo?**

Un ejemplo sencillo de una suma de a + b.

<img src="https://image.ibb.co/nkwp3y/tf_graph_2.png" alt="tf_graph_2" border="0" height="200">

Y aquí tenéis un ejemplo un poco más complicado, para los valientes:

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)

Es un ejemplo de un grafo que representa la clasificación de una imagen de un número en su correspondiente clase. No es necesario que entendáis lo que está ocurriendo, simplemente que tensorflow funciona así: primero tu defines las operaciones que quieres que se realicen, junto a las variables necearias (creas el grafo) y luego lo ejecutas (con una sesión). Pero basta de cháchara, ¡vamos a ponernos manos a la obra!


In [0]:
# Lo primero que debemos hacer es importar el paquete de Tensorflow
import tensorflow as tf
import matplotlib.pyplot as plt # importamos también pyplot para gráficas
%matplotlib inline

# Es muy importante que conozcamos 3 conceptos básicos de TF:
# tf.Graph: representa un conjunto de tf.Operations
# tf.Operation: son las operaciones indicadas por las ecuaciones que escribimos
# tf.Tensor: los resultados de las tf.Operations

# En un principio, el tf.Graph es transparente a nosotros, ya que por defecto
# existe uno donde se van añadiendo todas las operaciones que definimos:
# tf.get_default_graph()

In [0]:
# Vamos a empezar con algo muy sencillo, una simple multiplicación en TensorFlow

# Primero definimos los valores que queremos utilizar
x = tf.constant(6)  # tf.Constant porque no va a cambiar durante la ejecución
y = tf.constant(8)

# Ahora definimos la operación a realizar: la multiplicación
result = tf.multiply(x, y)
print(result)

Tensor("Mul:0", shape=(), dtype=int32)


In [0]:
# Como podéis ver, no nos ha devuelto el resultado. Lo que ha hecho hasta ahora
# ha sido crear el grafo. Por poner un ejemplo, es como montar un coche. Ahora 
# lo tenemos montado, pero aún no hace aquello para lo que fue diseñado, 
# desplazarse. Para ello, deberíamos encenderlo. Pues con esto es igual,
# tenemos que encenderlo:

sess = tf.Session()  # abrimos nuestro "coche" y lo encendemos
output = sess.run(result)  # nos ponemos en movimiento
print(output)

48


In [0]:
# Para poder visualizar el grafo es necesario definir un par de funciones que 
# lo permitan. No es necesario que les prestéis atención.

from IPython.display import clear_output, Image, display, HTML

def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))

In [0]:
# ahora sí, visualizamos el grafo recien construido:
show_graph(tf.get_default_graph().as_graph_def())